### PR TITLE
Instructions on how to get setup with the correct version of Zola

### PR DESCRIPTION
**Pull request by Chris-Petty**

### CODE REVIEW

**Review by roxy-dao — APPROVED** [review]
Thanks Chris!

**Comment by Chris-Petty** [comment]
I've had the gos, there is perhaps an easier way...

1. download [this](https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-apple-darwin.tar.gz) from https://github.com/getzola/zola/releases/tag/v0.17.2
2. Extract it and copy `zola` file to `/usr/local/bin/`
3. In a terminal try run Zola. It'll complain about malware, at which point you can allow it in settings 
image
4. Open/move a terminal window to the `msupply_docs` repo and run `zola serve`

**Comment by roxy-dao** [comment]
Easier for non-devs me thinks 😉

**Review by roxy-dao — APPROVED** [review]
Could have kept both non-dev and dev versions, but looks fine to me! 

Love the gos :kek:

**Comment by Chris-Petty** [comment]
As pressured @roxy-dao

**Pull request merged**
